spring:
  application:
    #应用名 (向注册中心注册就是使用这个名字)
    name: zuul
  cloud:
    config:
      #禁止配置中心的配置将客户端配置覆盖掉
      override-none: true
  rabbitmq:
    host: 192.168.64.140
    port: 5672
    username: admin
    password: admin
server:
  #端口
  port: 3001
  
eureka:
  client:
    #使用云服务提供的地址
    service-url:
      #使用自己地址 (没有云服务地址必须加这个)
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

#默认配置
zuul:
  #开启重试, zuul默认不推荐使用重试, 要测试的话要手动开启
  retryable: true
#  routes:
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000  #socket超时
#配置ribbon
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1